README.md
lib/plugin.js
spec/plugin.spec.js

Good work, this plugin is definitely what I needed. A few additions though:
* Make manifest filename configurable through constructor options.
* Adding `basePath` option for prefixing all filepaths within the manifest. This is useful for including the build output location within all file references.

Options and `basePath` addition

---

lib/plugin.js
spec/plugin.spec.js

ManifestPlugin currently doesn't handle sourcemap assets properly. `main.js.map` and `main.css.map` will result in a single output key, `main.map`. This is caused by the expectation of only a single file extension.
This is probably not the best way to solve this, but it works with minimal code changes. The `imageExtensions` RegExp was also changed to handle this. Additional extensions can easily be added for other modifiers. The change also includes a passing test for
Note: this branch is based off of [patch-1](https://github.com/jordansexton/webpack-manifest-plugin/tree/patch-1) (#3). I can change that and rebase if you like the PR but don't want to have to cherry pick around.

Added transformExtensions option for sourcemaps

---

lib/plugin.js
package.json
spec/plugin.spec.js

This fixes an issue I came across when trying to use this plugin with [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware)
`webpack-dev-middleware` uses [`memory-fs`](https://github.com/webpack/memory-fs) instead of writing to disk. 
The issue was that when the plugin tried to write the manifest [here](https://github.com/danethurber/webpack-manifest-plugin/blob/b29088eaf942500a19587f826f37cc34ded5f33e/lib/plugin.js#L73) it would crash because the output dir would not exist since webpack was writing the files to memory.
I changed the plugin so it emits the `manifest.json` as a standard asset so that webpack will write it using whichever fs it is currently using.
regarding a test...
I started writing a specific test for running with `memory-fs` but then realized …

Emit manifest with assets

---

lib/plugin.js

When running webpack in multi-compiler mode, several builds may be compiling different parts of the application (server, desktop client, mobile clients, templates, etc.)
The current behavior of the plugin is to initialize the manifest to an empty object. This PR adds an option to read the existing manifest file if it exists, rather than starting from scratch.
This allows multiple compilations using this plugin may essentially write to the same manifest file. I've used this in production for 2 months now with no conflicts, since the reads and writes occur synchronously.

Added readFile option

---

README.md
lib/plugin.js
spec/plugin.spec.js

This removes the sketchy extension whitelist for image types (refs. #11), and uses webpack's compilation events to solve a longstanding problem, how to map output assets possibly including hashes to inputs. I've run the tests and refactored until everything passed.
Edit: ~~This includes the two commits from #13, but I can cut them if there's a merge conflict.~~
It also overrides #11, but it actually solves the problem at the same time (manifest assets get uniquely associated with user inputs).

Handling of non-image, non-chunk assets; readFile changed

---

README.md
lib/plugin.js
spec/plugin.spec.js

this lets you generate a manifest that maps bundles/assets to public urls, similar to https://github.com/webpack/docs/wiki/configuration#outputpublicpath

add publicPath functionality

---

package.json

Lodash v3 is no longer supported, and it looks like v4 does not introduce any breaking changes for this package.
Can we increase the range of the supported lodash dependency to include v4 as proposed in this PR? 
This would avoid unmet peer dependency warnings on `npm install` when using a supported version of lodash.

increase lodash dependency version range

---

README.md
lib/plugin.js
package.json

When using this plugin is conjunction with [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) it will emit to memory only. This is preferred but in some use cases (eg. integration with rails) you also need the manifest file on the filesystem.
I've added a flag `writeToFileEmit` that will write the JSON output to the build folder as well.

Option to emit to file system

---

lib/plugin.js

feature: skip hot updates from manifest
fix: basePath was added to already cached manifest values on each compilation

Add webpack-dev-server support

---

lib/plugin.js
spec/plugin.spec.js

closes #46 _Do not add code splitting bundles into manifest_

fix: Only include initial chunks

---

lib/plugin.js
spec/plugin.spec.js

When populating the manifest, resolves `basePath`/`publicPath` with `key`/`value` (to resolve parent directory references).
So `/base/subfolder/../file.ext` becomes `/base/file.ext`.
Side benefit is trailing slashes on `basePath`/`publicPath` are now optional since `join` takes care of that for you.
Note that it uses `path.normalize(path.join())` instead of `path.resolve()` so that ancestors of `basePath`/`publicPath` are not exposed. (The approach could be simplified if that’s not a concern.) This results in invalid paths if an absolute path is specified with several parent directory references. E.g., `resolvePath('/absolute/../..', 'file.ext')` returns `'/file.ext'` (not valid), whereas `resolvePath('relative/../..', 'file.ext')` returns `'../file.ext'`.
<hr />
My particular use case …

Resolve paths

---

README.md
lib/plugin.js
spec/plugin.spec.js

closes #46 
closes #55 
closes #35

feat: add filter, map, reduce options

---

lib/plugin.js
spec/plugin.spec.js

Fix default manifest file mapping (path to name)

---

README.md
lib/plugin.js
spec/plugin.spec.js

BREAKING CHANGE:
- basePath is not ignored when publicPath is used
- basepath is only modifying manifest keys
closes #69

feat(basePath): use basePath for keys only

---

lib/plugin.js
spec/plugin.integration.spec.js

Hello there 😃 
My team has very specific needs for our build process and we are currently developing a Webpack Plugin that needs the entry and output filenames. We could do this on our own but it would be pointless to duplicate the code that is in the `webpack-manifest-plugin`. So we make a proposal to add a Webpack plugin hook to your plugin that will allow any plugin to hook itself to yours to pull the manifest.
I used the `applyPluginsAsync` function because the hook that I registered is post emit so no transformation could be applied and therefore there's no need to use waterfall or series.
I thought about adding also a hook before `Json.stringify` but I think that there's more probability that `webpack-manifest-plugin` hooks on other plugins to generate the manifest than other …

feat(plugin): Add plugin hook to allow other plugins to use the manifest

---

lib/plugin.js
spec/plugin.spec.js

fix: make sure paths are consistent from os to os

---

README.md
lib/plugin.js
spec/plugin.spec.js

BREAKING CHANGE: deprecate webpack-manifest-plugin's publicPath options in flavour of webpack's output.publicPAth
closes #65

feat: deprecate publicPath in flavour of webpack's

---

README.md
lib/plugin.js

BREAKING CHANGE: stripStr will not long have an effect on manifest keys
#81

feat: deprecate stripStr

---

lib/plugin.js
spec/plugin.spec.js

BREAKING CHANGE: 'cache' was renamed 'seed'

feat: deprecate cache in flavour of seed

---

README.md
lib/plugin.js
spec/plugin.spec.js

BREAKING CHANGE: reduce option replaced by generate option
closes #89 
@SeeThruHead Does that look goo to you?

feat: add generate option

---

README.md

Fixed some leftovers from #90. It's also quite confusing currently to have the docs for the new `generate` option, but it not being released yet. Any `opts.generate` is just silently ignored at the moment, I think either a release or backwards compatibility would be good.

docs: remove leftover reduce setting

---

.travis.yml
lib/plugin.js
package.json

Please review carefully, Im not sure the PR is complete. I have no deep knowledge of webpack plugin internals. 
I tested it in a small reference app and got a manifest generated.
Feedback appreciated.
Fixes #111

add support for webpack4

---

README.md
lib/plugin.js
spec/plugin.spec.js

Support different manifest output formats.
In my case I need to generate manifest as yaml to load it as symfony config. With this I can replace JSON.stringify with YAML.stringify in my webpack configuration.

add outputFormatter option

---

lib/plugin.js
package.json
spec/plugin.integration.spec.js

fix: use multiple instances at the same time 

---

lib/plugin.js
spec/plugin.integration.spec.js

fix(seed): reset seed on each emit

---

README.md
lib/plugin.js
spec/plugin.spec.js

We are using `create-react-app` and would like to generate the `index.html` file on the server. In order to get code splitting to work, we need to know which code chunks are entrypoints of the React app (to be able to request these from the HTML file).
In https://github.com/facebook/create-react-app/issues/5513#issuecomment-486838664, it was suggested to add an `"entrypoints"` key to `create-react-app`'s `asset-manifest.json` file with a list of these chunks (in the order they need to be included).
This PR passes an additional parameter called `entrypoints` to the `generate` function, which provides enough information to be able to build such a manifest file.

Pass `entrypoints` param to `generate` function

---

lib/plugin.js
package.json
spec/plugin.spec.js

I've introduced changes in #192 that aren't compatible with some older versions of Node.js. This PR fixes that. It can be reverted once the required Node.js version is increased.
Fixes #193

Fix `entrypoints` compatibility for older Node versions

---

.travis.yml
lib/plugin.js
package.json
spec/helpers/webpack-version-helpers.js
spec/plugin.integration.spec.js
spec/plugin.spec.js

This PR adds the `ids` objects to the stats retrieved by `stats.toJson()`.
It is needed by the latest alpha of Webpack 5 (`v5.0.0-alpha.31`) in order to retrieve `asset.chunks` later on (see https://github.com/webpack/webpack/pull/9793#pullrequestreview-300371456).
Without it, the following error is thrown by the plugin:
```
TypeError: Cannot read property 'length' of undefined
at (...)/node_modules/webpack-manifest-plugin/lib/plugin.js:128:39
```
Related: #186

Webpack 5: Add "ids" to the retrieved JSON stats

---

README.md

Updates README to note that fileName can accept a path to a location.

Update README to note abs output location option

---

lib/helpers.js

In response to and support of:
[Docs(api): add asset info for sourceFilename and javascriptModule #4116](https://github.com/webpack/webpack.js.org/pull/4116)
[feat: added `sourceFilename` with original file to asset info ](https://github.com/webpack-contrib/copy-webpack-plugin/pull/542)
Easing:
[Allow adding metadata to info #538](https://github.com/webpack-contrib/copy-webpack-plugin/issues/538)

feat: fallback to asset.info.sourceFilename

---

lib/hooks.js
test/unit/paths.js

This is a PR related to this issue I reported earlier: https://github.com/danethurber/webpack-manifest-plugin/issues/214
The fix is pretty straight forward, read publicPath from stats in order to handle the [hash] placeholders.

Read publicPath from stats to handle [hash]

---

lib/helpers.js
lib/hooks.js
lib/index.js
package.json
set-webpack-version.js
test/fixtures/import_image.js
test/integration/location.js
test/unit/index.js
test/unit/manifest-location.js
test/unit/paths.js

- [] no
List any relevant issue numbers: Fixes #238 and fixes #237 (also fixes https://github.com/symfony/webpack-encore/issues/907)
Hi!
I maintain @symfony/webpack-encore, and we recently upgraded to Webpack 5 and have hit issues with the `manifest.json` file. So, I dug into it :). 
This is complex, and I hope someone may have some ideas on how to make this nicer. Here is the situation:
A) As far as I (and the test suite) can tell, `chunk.auxiliaryFiles` is *only* needed to get sourcemap files. All other files are available in other ways. Since *all* `chunk.auxiliaryFiles` were used before, it caused #237 because …

Fixing extra and invalid paths in Webpack 5

---

package.json

List any relevant issue numbers: #270

Allow webpack 5 as peer dependency

---

src/hooks.ts

When `output.publicPath` is not ends with `/`, the path of output will be incorrect.
Webpack configuration:
```javascript
output: {
publicPath: '/public/js'
},
```
Wrong output:
```json
{
"index.js": "/public/jsindex.04565a72d083184c3c5a.js"
}
```
Correct output:
```json
{
"index.js": "/public/js/index.04565a72d083184c3c5a.js"
}
```

fix: properly join publicPath, basePath

---

src/index.ts

List any relevant issue numbers: #284 
According to READ.ME, "return_ anything as long as it's serialisable by JSON.stringify".
But when I started ts-check in my config file, I found `Manifest` type is `Record<string, string>` which is not quite fit into READ.ME.

fix: make manifest type match readme doc

---

README.md

Fixed a typo in the documentation for `seed` option in README.md

docs: fix typo in documentation for seed option

---

README.md

It seems this option text was misplaced.
Reading through the docs, I was a bit baffled as to how `assetHookStage` was intended to be used seeing as how it was listed next to `getCompilerHooks`, which is an export. The "Usage" section that immediately follows is also entirely unrelated to this functionality, which was confusing.
This also corrects the formatting to ensure the type and default values are on different lines, matching the rest of the options.

docs: Correct location of `assetHookStage` in readme

---

src/hooks.ts
src/index.ts

So I've somehow messed with dependency tree (with monorepo+linking) and webpack loaded twise. 
While you have setup webpack as peerDep and everything should be ok, I guess better to get webpack module provided instead of importing it. Also easier ts types

fix: only import webpack types

---

src/helpers.ts
src/index.ts
test/unit/generate.js

Webpack 5 deprecated a lot of the APIs that exist on chunks, and instead prefers the use of the ChunkGraph API. We have a few places where we use now-deprecated APIs in our usage of the WebpackManifestPlugin, and would like to move those over to using the ChunkGraph API.
This PR passes through the `chunkGraph` in the `generate` function

fix: Pass `chunkGraph` through in `generate` function
